In [1]:
import yfinance as yf
import pandas as pd

In [2]:
def get_historical_data(ticker):
  d = yf.Ticker(ticker)
  df = d.history(period="max")
  df.columns = df.columns.str.lower()
  df.columns = pd.Series(df.columns).str.capitalize().values
  return df.dropna()

In [3]:
df = get_historical_data('2330.TW')
df

,Open,High,Low,Close,Volume,Dividends,Stock splits
Date,,,,,,,
2000-01-04,36.830151,36.830151,36.209446,36.830151,200662321971,0.0,0.0
2000-01-05,36.830159,37.657780,36.416270,37.657780,402466776297,0.0,0.0
2000-01-06,37.450903,37.657771,36.830151,36.830151,197545701266,0.0,0.0
2000-01-07,35.588691,36.209444,35.174803,35.795555,235270327441,0.0,0.0
2000-01-10,36.830154,37.243882,36.209450,37.037018,276171665217,0.0,0.0
...,...,...,...,...,...,...,...
2020-11-13,459.000000,462.000000,456.500000,462.000000,31037438,0.0,0.0
2020-11-16,470.000000,484.500000,469.000000,484.000000,81994937,0.0,0.0
2020-11-17,502.000000,506.000000,485.500000,485.500000,72413868,0.0,0.0
2020-11-18,490.000000,497.000000,486.500000,497.000000,50387727,0.0,0.0
2020-11-19,499.000000,499.000000,490.000000,490.000000,44055000,0.0,0.0

In [4]:
import talib

# compute simple moving average using talib
sma1 = talib.SMA(df.Close, timeperiod=20)
sma2 = talib.SMA(df.Close, timeperiod=60)

# compute buy and sell signals (golden cross and death cross)
signal_long = (sma1 > sma2) & (sma1.shift() < sma2.shift())
signal_short = (sma1 < sma2) & (sma1.shift() > sma2.shift())

# combine long and short signals
signal = signal_long.copy()
signal[signal_short] = -1

ModuleNotFoundError: No module named 'talib'